---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP présente des limites de configuration du stockage dans Google Cloud pour assurer la fiabilité des opérations. Pour des performances optimales, ne configurez pas votre système aux valeurs maximales. 
---
= Limites de stockage dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP présente des limites de configuration du stockage pour assurer des opérations fiables. Pour des performances optimales, ne configurez pas votre système aux valeurs maximales.



== Capacité système maximale par licence

La capacité système maximale d'un système Cloud Volumes ONTAP est déterminée par sa licence. La capacité système maximale inclut le stockage sur disque et le stockage objet utilisé pour le Tiering des données.

NetApp ne prend pas en charge le dépassement de la limite de capacité système. Si vous atteignez la limite de capacité sous licence, BlueXP affiche un message d'action requise et ne vous permet plus d'ajouter des disques supplémentaires.

Pour certaines configurations, les limites de disque vous empêchent d'atteindre la limite de capacité en utilisant uniquement des disques. Vous pouvez atteindre la limite de capacité de https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["tiering des données inactives vers le stockage objet"^]. Pour plus de détails, reportez-vous aux limites de disques ci-dessous.

[cols="25,75"]
|===
| Licence | Capacité système maximale (disques + stockage objet) 


| Fréemium | 500 GO 


| PAYGO Explore | 2 To (le Tiering des données n'est pas pris en charge par Explore) 


| PAIEMENT À L'UTILISATION Standard | 10 TO 


| PAIEMENT À L'UTILISATION Premium | 368 TO 


| Licence basée sur les nœuds | 368 To par licence 


| Licence basée sur la capacité | 2 Pio 
|===
.Pour une paire HA, la capacité autorisée est-elle limitée par nœud ou par paire HA entière ?
La limite de capacité s'adresse à l'ensemble de la paire haute disponibilité. Il n'est pas par nœud. Par exemple, si vous utilisez la licence Premium, vous pouvez disposer d'une capacité maximale de 368 To entre les deux nœuds.

.Dans le cas d'une paire haute disponibilité, les données en miroir sont-elles prises en compte par rapport à la limite de capacité sous licence ?
Non, ce n'est pas le cas. Les données d'une paire HA sont mises en miroir de manière synchrone entre les nœuds, de sorte que les données soient disponibles en cas de défaillance dans Google Cloud. Par exemple, si vous achetez un disque de 8 To sur le nœud A, BlueXP alloue également un disque de 8 To sur le nœud B utilisé pour les données en miroir. Bien que 16 To de capacité aient été provisionnés, seulement 8 To comptent par rapport à la limite de licence.



== Limites de disque et de hiérarchisation

Le tableau ci-dessous présente la capacité maximale du système avec des disques seuls et des disques avec Tiering des données inactives vers le stockage objet. Les limites de disque sont spécifiques aux disques qui contiennent des données utilisateur. Les limites n'incluent pas le disque d'amorçage et le disque racine.

[cols="60,40"]
|===
| Paramètre | Limite 


| Nombre maximal de disques de données  a| 
* 124 pour les systèmes à un seul nœud
* 123 par nœud pour les paires haute disponibilité




| Taille maximale des disques | 64 TO 


| Capacité système maximale avec disques seuls | 256 TO ^1^ 


| Capacité système maximale avec disques et Tiering des données inactives vers un compartiment Google Cloud Storage | Dépend de la licence. Voir le tableau ci-dessus. 
|===
^1^ cette limite est définie par les limites des machines virtuelles dans Google Cloud Platform.



== Restrictions agrégées

Cloud Volumes ONTAP regroupe les disques Google Cloud Platform dans des _aggrégats_. Les agrégats fournissent du stockage aux volumes.

[cols="2*"]
|===
| Paramètre | Limite 


| Nombre maximal d'agrégats de données ^1^  a| 
* 99 pour un seul nœud
* 64 pour l'ensemble d'une paire haute disponibilité




| Taille maximale des agrégats | 256 To de capacité brute ^2^ 


| Disques par agrégat | 1-6 ^3^ 


| Nombre maximal de groupes RAID par agrégat | 1 
|===
Remarques :

. Le nombre maximal d'agrégats de données n'inclut pas l'agrégat racine.
. La limite de capacité de l'agrégat dépend des disques qui composent l'agrégat. La limite n'inclut pas le stockage objet utilisé pour le Tiering des données.
. Tous les disques qui composent un agrégat doivent être de la même taille.




== Limites de stockage logique

[cols="22,22,56"]
|===
| Stockage logique | Paramètre | Limite 


| *Machines virtuelles de stockage (SVM)* | Nombre maximal pour Cloud Volumes ONTAP (paire HA ou nœud unique) | Un SVM de service des données et un SVM de destination utilisés pour la reprise après incident. Vous pouvez activer le SVM de destination pour l'accès aux données en cas de panne sur le SVM source. ^1^ le SVM qui transmet les données couvre l'ensemble du système Cloud Volumes ONTAP (paire HA ou nœud unique). 


.2+| *Fichiers* | Taille maximale | 16 TO 


| Maximum par volume | Selon la taille du volume, jusqu'à 2 milliards 


| *Volumes FlexClone* | Profondeur de clone hiérarchique ^2^ | 499 


.3+| *Volumes FlexVol* | Maximale par nœud | 500 


| Taille minimale | 20 MO 


| Taille maximale | 100 TO 


| *Qtrees* | Maximum par volume FlexVol | 4,995 


| *Copies snapshot* | Maximum par volume FlexVol | 1,023 
|===
Remarques :

. BlueXP ne propose pas de prise en charge de l'orchestration ou de la configuration pour la reprise après incident des SVM. Il ne prend pas non plus en charge les tâches relatives au stockage sur une SVM supplémentaire. Vous devez utiliser System Manager ou l'interface de ligne de commande pour la reprise après incident SVM.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guide de préparation rapide pour la reprise après incident du SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guide de reprise après incident de SVM Express"^]


. La profondeur de clone hiérarchique correspond à la profondeur maximale d'une hiérarchie imbriquée de volumes FlexClone qui peut être créée à partir d'un seul volume FlexVol.




== Limites de stockage iSCSI

[cols="3*"]
|===
| Stockage iSCSI | Paramètre | Limite 


.4+| *LUN* | Maximale par nœud | 1,024 


| Nombre maximal de mappages de LUN | 1,024 


| Taille maximale | 16 TO 


| Maximum par volume | 512 


| *igroups* | Maximale par nœud | 256 


.2+| *Initiateurs* | Maximale par nœud | 512 


| Maximum par groupe initiateur | 128 


| *Sessions iSCSI* | Maximale par nœud | 1,024 


.2+| *Lifs* | Maximum par port | 1 


| Maximum par ensemble de ports | 32 


| *Porsets* | Maximale par nœud | 256 
|===