---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, nfsv3 
summary: Ces limitations connues sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. 
---
= Restrictions connues dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. N'oubliez pas de consulter également link:reference-limitations.html["Restrictions applicables dans tous les fournisseurs de cloud"].



== Limites de l'utilisation des extensions de machines virtuelles Azure

Dans un déploiement, Cloud Volumes ONTAP ne prend pas en charge les extensions de machines virtuelles et les applications de machines virtuelles Azure. L'utilisation d'Cloud Volumes ONTAP dans Azure avec des extensions de machine virtuelle entraîne des retards dans les opérations, et NetApp recommande de les éviter.



== Limites de Flash cache

Le type de machine virtuelle Standard_L8S_v2 inclut le stockage NVMe local, utilisé par Cloud Volumes ONTAP comme _Flash cache_. Notez les limitations suivantes pour Flash cache :

* La compression doit être désactivée sur tous les volumes pour tirer parti des améliorations des performances de Flash cache.
+
Vous pouvez choisir l'absence d'efficacité du stockage lors de la création d'un volume depuis BlueXP, ou vous pouvez créer un volume puis http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Désactiver la compression des données à l'aide de l'interface de ligne de commande"^].

* La réactivation du cache après un redémarrage n'est pas prise en charge avec Cloud Volumes ONTAP.




== Limitations de LA HAUTE DISPONIBILITÉ

Les limites suivantes affectent les paires HA Cloud Volumes ONTAP dans Microsoft Azure :

* NFSv4 n'est pas pris en charge. NFSv3 est pris en charge.
* Les paires HAUTE DISPONIBILITÉ ne sont pas prises en charge dans certaines régions.
+
https://bluexp.netapp.com/cloud-volumes-global-regions["Consultez la liste des régions Azure prises en charge"^]


